//
// Created by dev on 5/9/21.
//

#ifndef GAME_MASTERSOCKET_SERVER_GAME_SERVER_ENDPOINT_HPP
#define GAME_MASTERSOCKET_SERVER_GAME_SERVER_ENDPOINT_HPP


class game_server_endpoint {
};


#endif //GAME_MASTERSOCKET_SERVER_GAME_SERVER_ENDPOINT_HPP
